# Generated by Django 5.0.6 on 2024-08-06 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catname', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='pro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proname', models.TextField(max_length=50)),
                ('catname', models.TextField(max_length=50)),
                ('proimage', models.ImageField(default='null.jpg', upload_to='proimage')),
            ],
        ),
    ]
