# Generated by Django 5.0.6 on 2024-08-07 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0002_rename_catname_cat_cateogoryname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pro',
            name='productprice',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pro',
            name='productquantity',
            field=models.IntegerField(default=0),
        ),
    ]
