# Generated by Django 5.0.6 on 2024-08-08 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0003_pro_productprice_pro_productquantity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cat',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='pro',
            new_name='Product',
        ),
    ]
