# Generated by Django 5.0.6 on 2024-08-08 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0004_rename_cat_category_rename_pro_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cateogoryname',
        ),
        migrations.AddField(
            model_name='product',
            name='category_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.category'),
        ),
    ]
