# Generated by Django 5.0.6 on 2024-08-02 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='regi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=50)),
                ('phonenumber', models.IntegerField()),
                ('password', models.FloatField()),
            ],
        ),
    ]
