# Generated by Django 5.0.6 on 2024-08-11 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=50)),
                ('password', models.FloatField()),
            ],
        ),
        migrations.RenameModel(
            old_name='regi',
            new_name='Register',
        ),
    ]
