# Generated by Django 5.0.6 on 2024-08-12 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_login_rename_regi_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='email',
            field=models.EmailField(default=0, max_length=254),
        ),
    ]
