# Generated by Django 5.0.6 on 2024-08-19 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0003_register_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.CharField(max_length=123),
        ),
    ]
