# Generated by Django 5.0.6 on 2024-08-21 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0006_remove_cart_productimage_remove_cart_productname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='product_id',
            new_name='productname',
        ),
    ]
