# Generated by Django 5.0.6 on 2024-08-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0007_rename_product_id_cart_productname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='productname',
            new_name='product_id',
        ),
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cart',
            name='totalamount',
            field=models.IntegerField(default=0),
        ),
    ]
