# Generated by Django 5.0.6 on 2024-08-26 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0008_rename_productname_cart_product_id_cart_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='quantity',
            new_name='productquantity',
        ),
        migrations.AddField(
            model_name='cart',
            name='productimage',
            field=models.ImageField(default=0, upload_to=''),
        ),
        migrations.AddField(
            model_name='cart',
            name='productname',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='cart',
            name='productprice',
            field=models.IntegerField(default=0),
        ),
    ]
