# Generated by Django 5.0.6 on 2024-08-26 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0009_rename_quantity_cart_productquantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='productimage',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='productname',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='productprice',
        ),
    ]
