# Generated by Django 5.0.6 on 2024-08-26 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0010_remove_cart_productimage_remove_cart_productname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='productquantity',
            field=models.IntegerField(default=0),
        ),
    ]
