# Generated by Django 5.0.6 on 2024-08-26 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0011_alter_cart_productquantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='productquantity',
            field=models.IntegerField(default=1),
        ),
    ]
