# Generated by Django 5.0.6 on 2024-09-05 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0013_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='address',
            field=models.CharField(default=0, max_length=234),
        ),
        migrations.AddField(
            model_name='checkout',
            name='city',
            field=models.CharField(default=0, max_length=24),
        ),
        migrations.AddField(
            model_name='checkout',
            name='country',
            field=models.CharField(default=0, max_length=25),
        ),
        migrations.AddField(
            model_name='checkout',
            name='pincode',
            field=models.IntegerField(default=0),
        ),
    ]
