# Generated by Django 5.0.6 on 2024-09-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0014_checkout_address_checkout_city_checkout_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='city',
            field=models.CharField(default=0, max_length=244),
        ),
    ]
